### ISSUE TITLE
PyCharm can't install this dictionary

### ISSUE THREAD

**Issue by SalahAdDin** [EOM/Spell-Checking-PHPStorm-Spanish-dic-UTF8#2]
Hi, how are you?

I'm trying install this plugin but PyCharm can't do it:
![cantinstallspell](https://cloud.githubusercontent.com/assets/5034215/15784163/f1e709a4-2976-11e6-8958-ec169a58ac13.png)
 I have these error, then,i restart PyCharm and the SpellChecker isn't install, what happen with this? Thanks,

**Comment by EOM** [comment]
Hi, not test in PyCharm. Only in PHPstorm.

**Comment by coliveravenegas** [comment]
Hi, does it work in 2016 phpstorm?

**Comment by EOM** [comment]
Yes work in PHPstorm 2016, show install "[README.md](https://github.com/EOM/Spell-Checking-PHPStorm-Spanish-dic-UTF8)" only file "spanish-utf8.dic"
