### ISSUE TITLE
Doesn't installed correctly

### ISSUE THREAD

**Issue by raky291** [EOM/Spell-Checking-PHPStorm-Spanish-dic-UTF8#3]
Hi, I download your plugin from the interface [RubyMine](https://plugins.jetbrains.com/plugin/7851) but doesn't installed properly, and I don't understand why.

Solution: Download the .zip and add the "spanish-utf8.dic" to the list of dictionaries.

**Comment by kAlvaro** [comment]
In PhpStorm 10.0.1 it installs without issues and prompts for an IDE restart. Once you do so there's no trace of the plug-in: it's still listed as available and you're offered the "Install" action again.

I cannot find any reference to `SpellCheckerSpanishDictionary` in the IDE log. I'm running Windows 10 Pro.

**Comment by EOM** [comment]
Hi, not install Plugin.

Easy Solution: View README.md Place install manual

English: Installation Manual (PhpStorm >= 8)
1. Download "spanish-utf8.dic" and save it to the folder where you have installed PhpStorm "JetBrains/dic" (if there is no folder, create it).
2. Open the "Settings" window of PhpStorm (from the "File" menu), and within the "Editor -> Spelling" section adds "spanish-utf8.dic" to the list of dictionaries:
   Print config PHPStorm

**Comment by kAlvaro** [comment]
I'm confused. Is the plug-in abandoned?

**Comment by EOM** [comment]
Yes
