### ISSUE TITLE
No funciona en phpStorm 2016.2

### ISSUE THREAD

**Issue by jgrandar** [EOM/Spell-Checking-PHPStorm-Spanish-dic-UTF8#4]
Habría que adaptarlo a las nuevas versiones del IDE.

**Comment by kAlvaro** [comment]
It's a known issue but I believe the plug-in is no longer maintained. Please look at ticket #3 for further info.

In Spanish: el plug-in está abandonado.

**Comment by EOM** [comment]
Yes, the plug-in is abandoned.
Solution: View README.md Place install manual
Please look at [ticket #3](https://github.com/EOM/Spell-Checking-PHPStorm-Spanish-dic-UTF8/issues/3#issuecomment-233990802) for further info.
