### ISSUE TITLE
Not working for version 2016

### ISSUE THREAD

**Issue by francogp** [EOM/Spell-Checking-PHPStorm-Spanish-dic-UTF8#5]
Not compatible

**Comment by popkin** [comment]
Try this:
http://www.winedt.org/dict.html

and maybe:

1. Downloaded German (new sp) dictionary from that website
2. Extracted de_neu.dic file from zip archive and opened in Notepad++
3. Removed copyright comments
4. Converted from ANSI (or whatever encoding it was) to UTF-8 without BOM
5. Converted line ending from UNIX to Windows format (not sure if this is required)
6. Saved it somewhere in a separate folder (so only dictionary files are there)
7. In PhpStorm: Settings | Spelling | Dictionaries --> used "Add" button to add that folder
8. Make sure that file will have a tick next to the dictionary file
